# Generated by Django 5.1.3 on 2024-12-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("share", "0001_initial"),
        ("user", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("is_secreat", models.BooleanField()),
                ("message", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("cheer_up", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("message_summary", models.JSONField(default=dict)),
                (
                    "emotion_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="share.emotion",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
