# Generated by Django 5.1.3 on 2024-12-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diary", "0001_initial"),
        ("share", "0002_rename_emotion_emotions"),
        ("user", "0004_rename_user_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "diary_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diary.diary"
                    ),
                ),
                (
                    "emotion_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="share.emotions"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.users"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
