# Generated by Django 5.1.3 on 2024-12-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Emotion", new_name="Emotions",),
    ]
