# Generated by Django 5.1.3 on 2024-12-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
